cd bin
test1_aos_scalar_cpp.exe
test2_aos_scalar_cpp.exe
test3_aos_scalar_cpp.exe
test4_aos_scalar_cpp.exe

test1_aos_SSE_cpp.exe
test2_aos_SSE_cpp.exe
test3_aos_SSE_cpp.exe
test4_aos_SSE_cpp.exe
pause
